[package]
name = "goga_grabber"
version = "1.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.25.0", default-features = false, features = ["sync"] }
mega = { path = "mega-rs" }
reqwest = { version = "0.11.14", default-features = false, features = ["socks"] }
fastrand = "2.0.0"
futures = "0.3.28"
tokio-util = "0.7.7"
deadqueue = "0.2.4"
iced = { version = "0.9.0", features = ["tokio", "canvas", "svg"] }
iced_native = "0.10.3"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.96"
regex = "1.8.4"
num-traits = "0.2.15"
dark-light = "1.0.0"
native-dialog = "0.6.3"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
